### ISSUE TITLE
Incompatibility with Lucee 5.3.8

### ISSUE THREAD

**Issue by ivanionut** [coldbox-modules/qb#129] opened 2020-09-12 08:19 UTC
Hi @elpete,
today, to debug [this lucee bug](https://luceeserver.atlassian.net/jira/software/c/projects/LDEV/issues/LDEV-2898)  I upgraded to the lucee 5.3.8.70 but it would seem that `qb` (8.0.3) has some problems with this version.

Look at this code which first works with lucee lucee@5.3.6+61:

```

var q = qb()
    .from( "cart" )
    .where( "cart.session_id", "=", cookie.auth_Cart_id );

if( arguments.joinProducts ){
	q.leftJoin( "products_details", "cart.product_id", "products_details.product_id" );
	q.leftJoin( "products", "products_details.master_id", "products.master_id" );
}

if( arguments.joinProductMasterImage ){
	q.leftJoin( "products_images", "products_images.product_id", "products_details.product_id" );
}

dump( q.toSQL() ); abort;
```

with lucee 5.3.8.70 transform the query in this way (look `ON AND` ):

```\
SELECT * FROM `cart` LEFT JOIN `products_details` ON AND `cart`.`product_id` = `products_details`.`product_id` LEFT JOIN `products` ON AND `products_details`.`master_id` = `products`.`master_id` LEFT JOIN `products_images` ON AND `products_images`.`product_id` = `products_details`.`product_id` WHERE AND `cart`.`session_id` = ?
```

**Comment by elpete** [comment] 2020-09-24 16:52
Looks like a regression in Lucee: https://luceeserver.atlassian.net/browse/LDEV-3087

**Comment by elpete** [comment] 2020-09-24 17:04
Here's a PR to fix it: https://github.com/lucee/Lucee/pull/1049

**Comment by elpete** [comment] 2020-12-21 15:29
This was fixed by Lucee.

**Closed as completed by elpete** 2020-12-21 15:29 UTC
Labels: type: engine bug
