### ISSUE TITLE
Joins not working in update()

### ISSUE THREAD

**Issue by Daemach** [coldbox-modules/qb#162] opened 2021-04-05 15:42 UTC
I need to run the following query, but it's ignoring the JOIN statement so SQL chokes:

```
      qb.newQuery()
        .from('accounts a')
        .join('orderMarsData o', 'o.accountID', 'a.id')
        .where('orderID', arguments.id)
        .update({
          a.teTarget: qb.raw('o.track_err')
        })
```

Sorry to keep pushing the envelope :/

**Comment by Daemach** [comment] 2021-04-05 15:45
Should look like this:

```
          UPDATE a SET
          teTarget = o.track_err
          FROM accounts a
            JOIN orderMarsData o 
              ON a.id = o.accountID
```

**Comment by elpete** [comment] 2021-04-05 17:17
These are different between grammars which is one of the reasons I haven't added it yet. 

You can use `whereExists` to work around this for now.

**Comment by elpete** [comment] 2021-09-07 22:01
Duplicate of #172

**Closed as completed by elpete** 2021-09-07 22:01 UTC
Labels: type: bug, contributions: up for grabs, difficulty: medium
